site_name: JARVICE
theme: readthedocs
extra_css:
    - css/extra.css
nav:
    - Home: index.md
    - PushToCompute: cicd.md
    - Docker Images on JARVICE: docker.md
    - Nimbix Application Environment: nae.md
    - MPI Application Configuration Guide: mpi.md
    - Application Definition Guide: appdef.md
    - The JARVICE API: api.md
    - Resource Selection: machines.md
    - JARVICE job recipe: recipe.md
    - Public Applications: public.md
