site_name: JARVICE
theme: readthedocs
extra_css:
    - css/extra.css
pages:
    - Home: index.md
    - PushToCompute: cicd.md
    - Docker Images on JARVICE: docker.md
    - Nimbix Application Environment: nae.md
    - Application Definition Guide: appdef.md
    - The JARVICE API: api.md
    - JARVICE job recipe: recipe.md
    - Public Applications: public.md
    - Quickstart for SDaccel on JARVICE: sdaccel_quickstart.md
